name: aquatrade-fe
services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_STELLAR_NETWORK: ${NEXT_PUBLIC_STELLAR_NETWORK:-testnet}
        NEXT_PUBLIC_STELLAR_HORIZON_URL: ${NEXT_PUBLIC_STELLAR_HORIZON_URL:-https://horizon-testnet.stellar.org}
        NEXT_PUBLIC_STELLAR_FRIENDBOT_URL: ${NEXT_PUBLIC_STELLAR_FRIENDBOT_URL:-https://friendbot.stellar.org}
        NEXT_PUBLIC_STELLAR_EXPLORER_URL: ${NEXT_PUBLIC_STELLAR_EXPLORER_URL:-https://stellar.expert/explorer/testnet}
    ports:
      - "${HOST_PORT:-3000}:3000"
    restart: unless-stopped
